name: Deploy Main App to Cloud Run (Fixed)

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Ana uygulamayı deploy etmek istediğinize emin misiniz?'
        required: true
        default: 'true'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: namazvakti-api-fixed
  REGION: europe-west1
  REPOSITORY: namazvakti-repo
  LOCATION: europe-west1

jobs:
  deploy-main:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: "beta"

      # Docker kimlik doğrulaması
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker $LOCATION-docker.pkg.dev --quiet

      # Ana image oluştur
      - name: Build main container
        run: |
          docker build -t $LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE_NAME:latest .
          docker push $LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE_NAME:latest

      # Cloud Run servisine deploy et
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE_NAME:latest \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated \
            --set-env-vars="NODE_ENV=production,DEBUG=true" \
            --set-secrets="TURSO_DATABASE_URL=turso-database-url:latest,TURSO_AUTH_TOKEN=turso-auth-token:latest" \
            --memory 256Mi \
            --cpu 1 \
            --min-instances=0 \
            --max-instances=2 \
            --concurrency=80 \
            --timeout=300s \
            --verbosity=debug
  
      - name: Show deployed URL
        run: gcloud run services describe $SERVICE_NAME --region $REGION --format 'value(status.url)' 