name: Fetch Cities

on:
  workflow_dispatch:  # Manuel olarak tetiklenebilir
  schedule:
    - cron: '0 0 * * 0'  # Her Pazar gece yarısı çalışır (UTC)

jobs:
  fetch-cities:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Fetch cities data
        run: node src/scripts/fetchCities.js
      
      - name: Create summary
        run: echo "İlçe verileri başarıyla çekildi ve veritabanına kaydedildi." >> $GITHUB_STEP_SUMMARY 