name: Fetch Daily Content

on:
  schedule:
    # Her gün UTC 00:00'da çalışır (Türkiye saati ile 03:00)
    - cron: '0 0 * * *'
  workflow_dispatch: # Manuel tetikleme için

jobs:
  fetch-daily-content:
    name: Fetch Daily Content from Diyanet API
    runs-on: ubuntu-latest
    env:
      TURSO_DATABASE_URL: ${{ secrets.TURSO_DATABASE_URL }}
      TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
      HTTP_PROXY: ${{ secrets.HTTP_PROXY }}
      NODE_ENV: production
      GITHUB_ACTIONS: 'true'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Cache node modules
        uses: actions/cache@v3
        id: cache-npm
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Install dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm ci
      
      - name: Test Diyanet API Connection
        id: api-test
        run: |
          echo "Diyanet API'si bağlantısı test ediliyor..."
          echo "HTTP_PROXY değişkeni: ${{ env.HTTP_PROXY != '' && 'TANIMLANMIŞ ✅' || 'TANIMLANMAMIŞ ❌' }}" 
          node -e "
            const diyanetService = require('./src/services/diyanetService');
            
            async function testConnection() {
              try {
                console.log('Diyanet API bağlantısı test ediliyor...');
                await diyanetService.login();
                console.log('Diyanet API bağlantısı başarılı ✅');
              } catch (error) {
                console.error('Diyanet API bağlantı hatası:', error.message);
                process.exit(1);
              }
            }
            
            testConnection();
          "
        timeout-minutes: 5
        continue-on-error: true
      
      - name: Test Turso Database Connection
        id: db-test
        run: |
          echo "Turso veritabanı bağlantısı test ediliyor..."
          echo "TURSO_DATABASE_URL değişkeni: ${{ env.TURSO_DATABASE_URL != '' && 'TANIMLANMIŞ ✅' || 'TANIMLANMAMIŞ ❌' }}" 
          echo "TURSO_AUTH_TOKEN değişkeni: ${{ env.TURSO_AUTH_TOKEN != '' && 'TANIMLANMIŞ ✅' || 'TANIMLANMAMIŞ ❌' }}"
          node -e "const { testConnection } = require('./src/config/turso'); (async () => { try { await testConnection(); } catch(e) { console.error('Bağlantı hatası:', e); process.exit(1); } })();"
        continue-on-error: true
      
      - name: Fetch daily content
        id: fetch-content
        run: npm run fetch-daily-content
        timeout-minutes: 10
        continue-on-error: true
      
      - name: Log completion
        run: echo "Daily content fetch completed at $(date)"
      
      - name: Check for failures
        if: steps.api-test.outcome == 'failure' || steps.db-test.outcome == 'failure' || steps.fetch-content.outcome == 'failure'
        run: |
          echo "::error::Günlük içerik çekme işlemi başarısız oldu!"
          echo "API Testi: ${{ steps.api-test.outcome }}"
          echo "DB Testi: ${{ steps.db-test.outcome }}"
          echo "İçerik Çekme: ${{ steps.fetch-content.outcome }}"
          exit 1 