name: Fetch Prayer Times

on:
  workflow_dispatch:  # Sadece manuel olarak tetiklenebilir
  
jobs:
  fetch-prayer-times:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Fetch prayer times data
        run: node src/scripts/fetchPrayerTimes.js
        timeout-minutes: 240  # 4 saat timeout (uzun bir işlem olabilir)
      
      - name: Create summary
        run: echo "Namaz vakitleri başarıyla çekildi ve veritabanına kaydedildi." >> $GITHUB_STEP_SUMMARY 