name: Deploy Starter to Cloud Run

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Starter sürümü deploy etmek istediğinize emin misiniz?'
        required: true
        default: 'true'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: namazvakti-starter
  REGION: europe-west1
  REPOSITORY: namazvakti-repo
  LOCATION: europe-west1

jobs:
  deploy-starter:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: "beta"

      # Docker kimlik doğrulaması
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker $LOCATION-docker.pkg.dev --quiet

      # Starter container oluştur
      - name: Build starter container
        run: |
          docker build -t $LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE_NAME:latest -f Dockerfile.starter .
          docker push $LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE_NAME:latest

      # Cloud Run'a deploy et
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE_NAME:latest \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated \
            --set-env-vars="NODE_ENV=production" \
            --memory 256Mi \
            --cpu 1 \
            --min-instances=0 \
            --max-instances=1 \
            --concurrency=80 \
            --timeout=300s \
            --verbosity=debug
  
      - name: Show deployed URL
        run: |
          echo "Deployed URL:"
          gcloud run services describe $SERVICE_NAME --region $REGION --format 'value(status.url)' 